package com.cg.onlinehotelmanagementsystem.utility;

public interface IExceptionClass {
	String PERSON_EXCEED="NUMBER OF PERSONS EXCEED LIMIT";
	String ROOM_BOOKED="ROOM ALREADY BOOKED";
	String ERROR_IN_BOOKING="SOMETHING WENT WRONG";
	String WRONG_DATE="ENTER DATE IS NOT VALID";
	String WRONG_CITY="ENTER CITY IS WRONG";
	String SQL="SOMETHING WENT WRONG IN DATABASE";
	String CANCEL_BOOKING="NO BOOK ID FOUND";

}
